resources:
  repositories:
  - repository: templates
    type: git
    name: pinc/azure-pipeline-templates
    ref: refs/heads/master

trigger:
  batch: true
  branches:
    include:
    - master

steps:
- template: docker-build-push.yml@templates
- task: CopyFiles@2
  inputs:
    Contents: 'deployment.yml'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'