resources:
  repositories:
  - repository: templates
    type: git
    name: pinc/azure-pipeline-templates
    ref: refs/heads/develop

trigger:
  batch: true
  tags:
    include:
    - v*
  branches:
    include:
    - master
    - develop
    - feature/*  

jobs:
- template: job-templates/semver.yml@templates
- template: test-template.yml  
- job: sonar
  steps:
  - template: sonarqube-cli.yml@templates
- job: docker
  dependsOn: semver
  steps:
  - template: docker-build-push.yml@templates
- job: artefacts
  dependsOn:
  - tests
  steps:
  - task: CopyFiles@2
    inputs:
      Contents: |
        deployment.yml
        gitversion.json
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
