resources:
  repositories:
  - repository: templates
    type: git
    name: pinc/azure-pipeline-templates
    ref: refs/heads/master

trigger:
  batch: true
  branches:
    include:
    - master
    - develop
    - feature/*  

jobs:
- job: versioning
  steps:
  - powershell: |
      docker run --rm -v "$(pwd):/repo" gittools/gitversion:5.0.2-linux-centos-7-netcoreapp2.2 /repo > $(Build.SourcesDirectory)/gitversion.json
      $semver = Get-Content -Raw -Path $(Build.SourcesDirectory)/gitversion.json | ConvertFrom-Json
      $f = $semver.FullSemVer
      "##vso[task.setvariable variable=GITVERSION_FullSemVer;]$f"
      $s = $semver.SemVer
      "##vso[task.setvariable variable=GITVERSION_SemVer;]$s"
- job: sonar
  steps:
  - template: sonarqube-cli.yml@templates
- job: docker
  steps:
  - template: docker-build-push.yml@templates
- job: tests
  dependsOn:
  - docker
  steps:
  - script: |
      docker build --tag 'go-hello-world-builder:latest' --file Dockerfile.build .
      docker run --rm -v `pwd`:/src go-hello-world-builder:latest
    displayName: Build and Test go-hello-world executable
    workingDirectory: $(System.DefaultWorkingDirectory)
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura 
      summaryFileLocation: $(System.DefaultWorkingDirectory)/**/coverage.xml
      reportDirectory: $(System.DefaultWorkingDirectory)/**/coverage
- job: artefacts
  dependsOn:
  - tests
  steps:
  - task: CopyFiles@2
    inputs:
      Contents: 'deployment.yml'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
