resources:
  repositories:
  - repository: templates
    type: git
    name: pinc/azure-pipeline-templates
    ref: refs/heads/master

trigger:
  batch: true
  branches:
    include:
    - master

jobs:
- template: steps-templates/semver.yml@templates
- job: sonar
  dependsOn:
  - semver
  steps:
  - template: sonarqube-cli.yml@templates
- job: docker
  dependsOn:
  - semver
  steps:
  - template: docker-build-push.yml@templates
- job: tests
  dependsOn:
  - docker
  steps:
  - script: |
      docker build --tag 'go-hello-world-builder:latest' --file Dockerfile.build .
      docker run --rm -v `pwd`:/src go-hello-world-builder:latest
    displayName: Build and Test go-hello-world executable
    workingDirectory: $(System.DefaultWorkingDirectory)
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura 
      summaryFileLocation: $(System.DefaultWorkingDirectory)/**/coverage.xml
      reportDirectory: $(System.DefaultWorkingDirectory)/**/coverage
- job: artefacts
  dependsOn:
  - tests
  steps:
  - task: CopyFiles@2
    inputs:
      Contents: 'deployment.yml'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
