resources:
  repositories:
  - repository: templates
    type: git
    name: pinc/azure-pipeline-templates
    ref: refs/heads/bugfix/fix-missing-semver

trigger:
  batch: true
  tags:
    include:
    - v*
  branches:
    include:
    - master
    - develop
    - feature/*  

jobs:
- template: test-template.yml  
- job: sonar
  steps:
  - template: sonarqube-cli.yml@templates
- job: docker
  dependsOn: 
  - semver
  - tests  
  steps:
  - template: docker-build-push.yml@templates
- job: artefacts
  dependsOn:
  - tests
  steps:
  - task: CopyFiles@2
    inputs:
      Contents: |
        deployment.yml
      TargetFolder: '$(Build.ArtifactStagingDirectory)/manifests'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/manifests'
      ArtifactName: 'manifests'
