resources:
  repositories:
  - repository: templates
    type: git
    name: pinc/azure-pipeline-templates
    ref: refs/heads/master

trigger:
  batch: true
  branches:
    include:
    - master

steps:
- template: docker-build-push.yml@templates
