apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: go-hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-hello-world
  template:
    metadata:
      labels:
        app: go-hello-world
    spec:
      hostNetwork: false
      containers:
      - name: go-hello-world
        image: docker.na1.hsdp.io/wellcentive/go-hello-world:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080  
        resources:
          limits: {}
      imagePullSecrets:
      - name: docker.na1.hsdp.io
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: go-hello-world
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: hello-world.terrakube.com
    http:
      paths:
      - backend:
          serviceName: go-hello-world
          servicePort: 8080
