# syntax = docker/dockerfile:1-experimental

FROM golang:1.17.2 as builder
WORKDIR /build
COPY go.mod .
COPY go.sum .
RUN go mod download

# Build
COPY . .
RUN --mount=type=cache,target=/root/.cache/go-build \
  CGO_ENABLED=0 go build -o app

FROM alpine:latest
RUN apk update && apk add ca-certificates && apk add postgresql-client && rm -rf /var/cache/apk/*
WORKDIR /app
COPY --from=builder /build/app /app
EXPOSE 8080
CMD ["/app/app"]
