FROM golang:1.16.6-buster as builder
LABEL maintainer="andy.lo-a-foe@philips.com"
WORKDIR /go-hello-world
COPY go.mod .
#COPY go.sum .

# Get dependencies - will also be cached if we won't change mod/sum
RUN go mod download

# Build
COPY . .
RUN go build .

FROM registry.access.redhat.com/ubi8/ubi-minimal
WORKDIR /app
COPY --from=builder /go-hello-world/go-hello-world /app
EXPOSE 8080
ENTRYPOINT ["/app/go-hello-world"]
