jobs:
- job: tests
  steps:
  - script: |
      docker build --tag 'go-hello-world-builder:latest' --file Dockerfile.build .
      docker run --rm -v `pwd`:/src go-hello-world-builder:latest
    displayName: Build and Test go-hello-world executable
    workingDirectory: $(System.DefaultWorkingDirectory)
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura 
      summaryFileLocation: $(System.DefaultWorkingDirectory)/**/coverage.xml
      reportDirectory: $(System.DefaultWorkingDirectory)/**/coverage
