apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: go-hello-world
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: go-hello-world
  endpoints:
    - port: http-metrics
      path: /metrics
