apiVersion: v1
kind: Service
metadata:
  name: go-hello-world
  namespace: ${namespace}
  labels:
    app.kubernetes.io/name: go-hello-world
    app.kubernetes.io/instance: go-hello-world
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 9100
      targetPort: 9100
      protocol: TCP
      name: http-metrics
  selector:
    app.kubernetes.io/instance: go-hello-world
    app.kubernetes.io/name: go-hello-world
