name: ko tagged

on:
  push:
    tags:
    - '*'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v2
        with:
          # We must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head.
          fetch-depth: 2
      - 
        name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      -
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20.3'
          check-latest: true
          cache-dependency-path: go.sum
      -
        name: Log in to the Github Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: KO setup
        uses: ko-build/setup-ko@v0.6
        env:
          KO_DOCKER_REPO: ghcr.io/loafoe
      - 
        name: Build and push
        run: ko build --tags ${{ steps.vars.outputs.tag }} -B
